import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { once } from 'node:events';
import { openStore } from '../server/store.mjs';
import { createApp } from '../server/server.js';
import { seedBytes, originalPath, hasPrivateInput } from './fixture.mjs';

const owner = 'owner-test-only-not-a-live-secret-123456';
const coach = 'coach-test-only-not-a-live-secret-123456';
const viewer = 'viewer-test-only-not-a-live-secret-123456';
test('API可靠保存、同ID更新、权限、冲突、回收站和恢复', async t => {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'nico-tests-'));
  const fixture = JSON.parse(seedBytes);
  // These explicitly named test-only records contain no invented measurements.
  for (const key of ['trainings', 'fitness', 'nutrition']) fixture[key] = [{ id: 'fixture-A', date: fixture.growth[0].date }, { id: 'fixture-B', date: fixture.growth[1].date }];
  fs.writeFileSync(path.join(directory, 'seed.json'), JSON.stringify(fixture));
  const store = openStore({ filename: path.join(directory, 'state.sqlite'), seedPath: path.join(directory, 'seed.json'), backupDir: path.join(directory, 'backups') });
  const server = createApp({ store, uploadsDir: path.join(directory, 'uploads'), releaseDir: path.join(directory, 'release'), authRequired: true, tokens: { owner, coach, viewer }, processUploads: false }).listen(0, '127.0.0.1');
  await once(server, 'listening');
  t.after(async () => { server.closeAllConnections(); await new Promise(resolve => server.close(resolve)); store.close(); fs.rmSync(directory, { recursive: true, force: true }); if (hasPrivateInput) assert.deepEqual(fs.readFileSync(originalPath), seedBytes); });
  const base = `http://127.0.0.1:${server.address().port}`;
  let rev = store.read().revision;
  const request = async (url, method = 'GET', body, token = owner, revision = rev) => {
    const response = await fetch(base + url, { method, headers: { ...(token ? { Authorization: `Bearer ${token}` } : {}), 'Content-Type': 'application/json', 'If-Match': String(revision) }, body: body === undefined ? undefined : JSON.stringify(body) });
    const next = response.headers.get('X-Nico-Revision'); if (next) rev = Number(next);
    return { status: response.status, data: await response.json() };
  };
  assert.equal((await request('/api/snapshot', 'GET', undefined, '')).status, 401);
  assert.equal((await request('/api/snapshot', 'GET', undefined, viewer)).status, 200);
  assert.equal((await request('/api/profile', 'PUT', { name: 'Nico', sex: '', birthDate: '' }, coach)).status, 403);
  assert.equal((await request('/api/backup', 'GET', undefined, viewer)).status, 403);
  const foreign = await fetch(base + '/api/snapshot', { headers: { Authorization: `Bearer ${owner}`, Origin: 'https://unapproved.example' } }); assert.equal(foreign.status, 403);
  const mediaPath = `/api/media/${fixture.media[0].id}/content/original`;
  assert.equal((await fetch(base + mediaPath)).status, 401);
  const upload = async (token, title, revision = rev, filename = 'protocol-test.png', mime = 'image/png') => {
    const body = new FormData(); body.append('date', '2026-10-06'); body.append('title', title);
    // Fixed protocol bytes in the isolated test server; media probing is disabled here.
    body.append('file', new Blob(['protocol-only-no-real-media'], { type: mime }), filename);
    const response = await fetch(base + '/api/media', { method: 'POST', headers: { Authorization: `Bearer ${token}`, 'If-Match': String(revision) }, body });
    return { status: response.status, data: await response.json() };
  };
  const beforeUploads = store.read();
  assert.equal((await upload(coach, '无权上传测试')).status, 403);
  assert.equal((await upload(owner, '错误格式测试', rev, 'test.exe', 'application/octet-stream')).status, 400);
  assert.equal((await upload(owner, '')).status, 400);
  assert.equal((await upload(owner, '   ')).status, 400);
  assert.equal((await upload(owner, '过期版本上传测试', 0)).status, 409);
  assert.deepEqual(store.read(), beforeUploads);
  assert.deepEqual(fs.readdirSync(path.join(directory, 'uploads')), []);
  for (const key of ['trainings', 'fitness', 'nutrition']) {
    const response = await request(`/api/${key}/fixture-A`, 'PUT', { date: '2026-10-06' }); assert.equal(response.status, 200); assert.equal(response.data.id, 'fixture-A');
  }
  const planInput = { title: '接口测试计划（不写真实库）', startDate: '2026-10-06', endDate: '2026-10-06', focus: '校验版本保存', status: '草稿', sessions: [], sourceIds: [fixture.swim[3].id] };
  const beforeEmptyPlan = store.read();
  for (const field of ['title', 'focus']) assert.equal((await request('/api/plans', 'POST', { ...planInput, [field]: '   ' })).status, 400);
  assert.deepEqual(store.read(), beforeEmptyPlan);
  const plan = await request('/api/plans', 'POST', planInput); assert.equal(plan.status, 201); assert.equal(plan.data.version, 1);
  const changedPlan = await request(`/api/plans/${plan.data.id}`, 'PUT', { focus: '校验历史保留' }); assert.equal(changedPlan.data.version, 2); assert.equal(store.read().data.planHistory.at(-1).version, 1);
  assert.equal((await request('/api/plans', 'POST', { ...planInput, sourceIds: ['nonexistent'] })).status, 400);
  const annotationInput = { mediaId: fixture.media[0].id, startSecond: 0, endSecond: 1, observation: '仅用于参数测试，不作技术诊断', status: '草稿' };
  assert.equal((await request('/api/annotations', 'POST', annotationInput, coach)).status, 201);
  assert.equal((await request('/api/annotations', 'POST', { ...annotationInput, status: '已审核', reviewedBy: '测试审核人' }, coach)).status, 400);
  for (const body of [{ totalMeters: -100, kickMeters: 900, rpe: 99, completionRate: 150 }, { totalMeters: 0, kickMeters: 1 }, { rpe: 0 }]) assert.equal((await request('/api/trainings', 'POST', { date: '2026-10-06', ...body })).status, 400);
  assert.equal((await request('/api/swim', 'POST', { ...Object.fromEntries(['date','distance','stroke','time','poolLength'].map(k => [k, fixture.swim[0][k]])), time: 'abc' })).status, 400);
  const zero = await request('/api/trainings', 'POST', { date: '2026-10-06', completionRate: 0 }); assert.equal(zero.status, 201); assert.equal(zero.data.completionRate, 0); assert.equal(zero.data.totalMeters, null);
  assert.equal((await request('/api/trainings/fixture-A', 'PUT', { date: '2026-10-07' }, owner, 1)).status, 409);
  const backup = (await request('/api/backup')).data;
  const deleted = await request(`/api/trainings/${zero.data.id}`, 'DELETE'); assert.equal(deleted.status, 200);
  const trash = store.read().data.trash.at(-1); assert.equal((await request(`/api/trash/${trash.id}/restore`, 'POST')).status, 200);
  assert.equal((await request('/api/restore', 'POST', backup)).status, 200); assert.deepEqual(store.read().data, backup.data);
  assert.equal((await request('/api/publishing', 'PUT', { swimIds: [fixture.swim[0].id], mediaIds: [], story: '测试导出范围', confirmedBy: '测试确认人', confirmedAt: '2026-10-06' })).status, 200);
  assert.equal((await request('/api/public-export', 'POST')).status, 200);
  const release = JSON.parse(fs.readFileSync(path.join(directory, 'release/public-summary.json'), 'utf8'));
  assert.equal(release.swim.length, 1); assert.equal(release.swim[0].notes, undefined); assert.equal(release.growth, undefined);
  assert.equal((await request('/api/restore', 'POST', { format: 'nico-backup-v1', data: { swim: null } })).status, 400);
  const malformedPlanBackup = structuredClone(backup); malformedPlanBackup.data.plans[0].sessions = null;
  const beforeBadRestore = store.read();
  assert.equal((await request('/api/restore', 'POST', malformedPlanBackup)).status, 400);
  assert.deepEqual(store.read(), beforeBadRestore);
  const malformedMediaBackup = structuredClone(backup); malformedMediaBackup.data.media[0].duration = 'invalid-duration';
  assert.equal((await request('/api/restore', 'POST', malformedMediaBackup)).status, 400);
  const malformedMeasurementBackup = structuredClone(backup); malformedMeasurementBackup.data.trainings[0].rpe = 99;
  assert.equal((await request('/api/restore', 'POST', malformedMeasurementBackup)).status, 400);
  const malformedTextBackup = structuredClone(backup); malformedTextBackup.data.media[0].title = { invalid: '协议测试，不是文字' };
  assert.equal((await request('/api/restore', 'POST', malformedTextBackup)).status, 400);
  const malformedBooleanBackup = structuredClone(backup); malformedBooleanBackup.data.nutrition[0].calciumTaken = 'false';
  assert.equal((await request('/api/restore', 'POST', malformedBooleanBackup)).status, 400);
  const malformedTrashBackup = structuredClone(backup); malformedTrashBackup.data.trash = [{ id: 'invalid-trash', collection: 'media', record: { ...malformedTextBackup.data.media[0] } }];
  assert.equal((await request('/api/restore', 'POST', malformedTrashBackup)).status, 400);
  assert.deepEqual(store.read(), beforeBadRestore);
  const before = store.read(); fs.rmSync(path.join(directory, 'backups'), { recursive: true }); fs.writeFileSync(path.join(directory, 'backups'), 'block-backup-write');
  assert.equal((await request('/api/trainings/fixture-A', 'PUT', { date: '2026-10-07' })).status, 500); assert.deepEqual(store.read(), before);
});
test('坏种子文件不会被空库替代', () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'nico-corrupt-')); fs.writeFileSync(path.join(dir, 'seed.json'), '{broken');
  assert.throws(() => openStore({ filename: path.join(dir, 'db.sqlite'), seedPath: path.join(dir, 'seed.json'), backupDir: path.join(dir, 'backups') }));
  fs.rmSync(dir, { recursive: true, force: true });
});
