import { useState } from 'react';
import { analysis, best, eventRecords, parseTime, timeLabel, latest, FIELDS } from '../../shared/domain.mjs';
import { Empty, Modal } from './ui';
export default function Dashboard({ data, navigate }) {
  const result = analysis(data), pb25 = best(data.swim, '25m', '自由泳', '25m'), growth = latest(data.growth);
  const activePlan = [...data.plans].reverse().find(p => p.status === '已确认');
  const values = eventRecords(data.swim);
  const [sourceId, setSourceId] = useState(null);
  const sourceCollection = Object.keys(FIELDS).find(key => data[key]?.some(r => r.id === sourceId));
  const source = sourceCollection && data[sourceCollection].find(r => r.id === sourceId);
  return <div className="stack"><header className="page-header"><div><p className="eyebrow">依据你录入的记录</p><h1>{data.profile.name || 'Nico'}的游泳成长</h1><p className="muted">最近成绩记录：{result.recent?.date || '尚未录入'}</p></div><button className="apple-btn apple-btn-primary" onClick={() => navigate('records', 'trainings')}>记录本次训练</button></header>
    <section className="focus-card"><span className="eyebrow">{activePlan ? '教练已确认的周期重点' : '当前待教练确认的重点'}</span><h2>{activePlan?.focus || result.focus}</h2><p>{activePlan ? `计划${activePlan.title} · 版本${activePlan.version} · 确认人${activePlan.reviewedBy}` : '依据最新成绩备注生成建议草稿；具体课表、练习量和技术判断待教练确认。'}</p><button onClick={() => navigate('week')}>查看本周与提升计划 →</button></section>
    <section className="fact-grid"><Fact label="50米自由泳 · 50米池PB" value={result.pb ? timeLabel(parseTime(result.pb.time)) : '未记录'} detail={result.pb?.date}/><Fact label="25米自由泳 · 25米池PB" value={pb25 ? timeLabel(parseTime(pb25.time)) : '未记录'} detail={pb25?.date}/><Fact label="最近身体测量" value={growth?.date || '未记录'} detail="只展示测量，不推断竞技天赋"/></section>
    <section className="glass-card"><h2>数据覆盖</h2><div className="coverage-grid">{[['trainings', '水上训练'], ['fitness', '体能测量'], ['nutrition', '恢复与饮食']].map(([key, label]) => <button key={key} onClick={() => navigate('records', key)}><strong>{data[key].length}条</strong><span>{label}</span><small>{data[key].length ? '查看实际记录' : '未记录 · 未评估'}</small></button>)}</div></section>
    <section className="glass-card"><h2>50米自由泳成绩 · 50米池</h2><p className="muted">不同项目分别统计。出发与计时条件未知时，只呈现记录变化。</p>{!values.length ? <Empty/> : <><svg className="trend" viewBox="0 0 600 160" role="img" aria-label="已录入的长池50米自由泳成绩变化，具体值见下方列表"><polyline fill="none" stroke="#1764bb" strokeWidth="3" points={values.map((r, i) => `${40 + (i * 520 / Math.max(1, values.length - 1))},${20 + (parseTime(r.time) - Math.min(...values.map(x => parseTime(x.time)))) / Math.max(1, Math.max(...values.map(x => parseTime(x.time))) - Math.min(...values.map(x => parseTime(x.time)))) * 95}`).join(' ')}/>{values.map((r, i) => { const x = 40 + i * 520 / Math.max(1, values.length - 1), y = 20 + (parseTime(r.time) - Math.min(...values.map(x => parseTime(x.time)))) / Math.max(1, Math.max(...values.map(x => parseTime(x.time))) - Math.min(...values.map(x => parseTime(x.time)))) * 95; return <g key={r.id}><circle cx={x} cy={y} r="5" fill="#1764bb"/><text x={x} y={y + 23} textAnchor="middle">{parseTime(r.time).toFixed(2)}s</text></g>; })}</svg><ul className="data-list">{values.map(r => <li key={r.id}><button onClick={() => navigate('records', 'swim')}>{r.date} · {r.time} · {r.recordType || '性质未知'} · {r.timingMethod || '计时未知'}</button></li>)}</ul></> }</section>
    <section className="glass-card"><h2>当前分析 · {result.version}</h2><p className="muted">事实、原始记录与待验证建议分别标注；没有自动天赋评分或成绩预测。</p><ul className="fact-list">{result.facts.map((fact, i) => <li key={i}><span className="badge">{fact.kind}</span><p>{fact.text}</p><small>依据：{fact.sourceIds.length ? fact.sourceIds.map(id => <button className="source-button" key={id} onClick={() => setSourceId(id)}>{Object.keys(FIELDS).map(key => data[key]?.find(r => r.id === id)).filter(Boolean).map(r => `${r.date || r.deadline || '目标'} · ${r.distance ? `${r.distance}${r.stroke}` : r.category || '原始测量'}`).join('')}</button>) : '当前集合记录数量'}</small></li>)}</ul><div className="actions"><button onClick={() => navigate('review')}>生成本周报告 →</button><button onClick={() => navigate('profile')}>查看个人目标 →</button></div></section>
    {source && <Modal title={`原始记录 · ${source.id}`} onClose={() => setSourceId(null)}><p className="muted">以下为原始输入，未确认的目标或备注不作为训练指令。</p><dl className="record-fields">{FIELDS[sourceCollection].map(f => <div key={f.key}><dt>{f.label}</dt><dd>{String(source[f.key] ?? '未填写')}</dd></div>)}</dl></Modal>}
  </div>;
}
function Fact({ label, value, detail }) { return <article className="glass-card fact"><p>{label}</p><strong>{value}</strong><small>{detail || '无实测时留空'}</small></article>; }
