import { downloadJSON } from '../services/files';
import { useState } from 'react';
import { FIELDS, analysis, validateRecord, fingerprint } from '../../shared/domain.mjs';
import { Field, Message, Empty } from './ui';
export default function PlanViewer({ data, api, onSaved, readOnly }) {
  const result = analysis(data);
  const blank = () => Object.fromEntries(FIELDS.plans.map(f => [f.key, '']));
  const [form, setForm] = useState(blank), [sessions, setSessions] = useState([]), [editing, setEditing] = useState(null), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  const [baseRevision, setBaseRevision] = useState(() => api.getRevision()), [conflict, setConflict] = useState(false);
  const update = (i, key, value) => setSessions(current => current.map((s, n) => n === i ? { ...s, [key]: value } : s));
  const payload = () => ({ ...form, sessions, sourceIds: result.sourceIds, sourceVersion: result.version });
  const submit = async e => {
    e.preventDefault(); setBusy(true); setError('');
    try { const previous = data.plans.find(p => p.id === editing); validateRecord('plans', payload(), previous); const saved = await api.request(`/api/plans${editing ? `/${editing}` : ''}`, { method: editing ? 'PUT' : 'POST', body: payload(), expectedRevision: baseRevision }); onSaved('plans', saved); setForm(blank()); setSessions([]); setEditing(null); setBaseRevision(api.getRevision()); } catch (problem) { setError(problem.message); setConflict(problem.status === 409); } finally { setBusy(false); }
  };
  return <div className="stack"><header><h1>本周与训练提升计划</h1><p className="muted">依据当前记录生成的4周管理建议；具体组数、强度、休息由现场教练安排。</p></header>
    <section className="glass-card"><h2>当前重点：{result.focus}</h2><p>来源：{result.recent ? `${result.recent.date} · ${result.recent.id} · ${result.recent.notes || '无备注'}` : '尚无成绩，先建立记录基线'}</p><p className="muted">出发、计时、分段与体能资料不足，不推断快肌状态、不相加提速秒数、不把25米乘2换算50米。</p></section>
    <div className="stage-grid">{result.stages.map(stage => <article className="glass-card" key={stage.title}><h2>{stage.title}</h2><p>{stage.action}</p><p className="muted">交付：{stage.delivery}</p><span className="badge">建议草稿 · 待教练确认</span></article>)}</div>
    <section className="glass-card"><h2>执行与恢复边界</h2><ul className="data-list"><li>不安排家庭水下憋气任务或强制限气口令，水下技能须有合格现场监督。</li><li>家庭额外活动计入总负荷。具体运动由教练确认；有疼痛、不适、反复疲惫或厌训时先沟通。</li><li>记录实际课表与休息日；不因年龄或网页模板自动追加每天的弹跳、拉伸和补充剂。</li><li>长池50米没有半程转身；短池相关技术单独记录。</li></ul><p className="muted">资料：<a href="https://www.redcross.org/content/dam/redcross/training-services/scientific-advisory-council/2022%20Hypoxic%20Blackout%20-%20Joint%20Statement%20-%20Red%20Cross%20Y%20USA%20Swimming%2010-31-2022.pdf" target="_blank" rel="noreferrer">水上呼吸安全联合声明</a> · <a href="https://publications.aap.org/pediatrics/article/153/2/e2023065129/196435" target="_blank" rel="noreferrer">AAP儿童运动负荷资料</a> · <a href="https://aasm.org/advocacy/position-statements/child-sleep-duration-health-advisory/" target="_blank" rel="noreferrer">睡眠参考</a></p></section>
    <h2>已保存的周期与课次</h2>{!data.plans.length && <Empty>尚无已保存计划；以上建议没有被当作已执行课表。</Empty>}
    {data.plans.map(p => <PlanCard key={p.id} plan={p} stale={p.sourceVersion && p.sourceVersion !== result.version} onEdit={readOnly ? null : () => { setBaseRevision(api.getRevision()); setEditing(p.id); setForm(Object.fromEntries(FIELDS.plans.map(f => [f.key, p[f.key] ?? '']))); setSessions(structuredClone(p.sessions || [])); }}/>) }
    {!readOnly && <details className="glass-card" open={Boolean(editing)}><summary>{editing ? '编辑计划并保存新版本' : '创建计划与课次'}</summary><Message error>{error}</Message>{conflict && <Message>刷新记录并核对当前计划后，<button onClick={() => { setBaseRevision(api.getRevision()); setConflict(false); }}>使用已核对的新版本重试</button></Message>}<button onClick={() => setForm(current => ({ ...current, title: '基于当前记录的周期复盘', focus: result.focus, status: '草稿' }))}>用当前建议填写草稿重点</button><form onSubmit={submit}><div className="form-grid">{FIELDS.plans.map(f => <Field key={f.key} field={f} value={form[f.key]} onChange={value => setForm(current => ({ ...current, [f.key]: value }))}/>)}</div>
      <h3>课次与组表（填写教练安排，不自动生成泳程）</h3>{sessions.map((s, i) => <fieldset key={s.id}><legend>课次{i + 1}</legend><div className="form-grid"><Field field={{ key: 'date', label: '日期', type: 'date', required: true }} value={s.date} onChange={v => update(i, 'date', v)}/><Field field={{ key: 'type', label: '类型', type: 'select', options: ['训练', '休息', '待确认'], required: true }} value={s.type} onChange={v => update(i, 'type', v)}/><Field field={{ key: 'title', label: '名称', type: 'text' }} value={s.title} onChange={v => update(i, 'title', v)}/><Field field={{ key: 'durationMinutes', label: '计划时长（分钟）', type: 'number', min: 0, max: 600 }} value={s.durationMinutes} onChange={v => update(i, 'durationMinutes', v)}/><Field field={{ key: 'poolLength', label: '池长', type: 'select', options: ['25m', '50m'] }} value={s.poolLength} onChange={v => update(i, 'poolLength', v)}/><Field field={{ key: 'startType', label: '出发方式', type: 'select', options: ['跳台', '蹬壁', '水中', '未知'] }} value={s.startType} onChange={v => update(i, 'startType', v)}/></div>
        {s.sets.map((g, n) => <div className="set-row" key={n}>{[['task', '任务', 'text'], ['repeats', '次数', 'number'], ['distance', '每次距离（m）', 'number'], ['restSeconds', '休息（秒）', 'number']].map(([key, label, type]) => <Field key={key} field={{ key, label, type, required: true, min: key === 'restSeconds' ? 0 : 1 }} value={g[key]} onChange={value => update(i, 'sets', s.sets.map((item, j) => j === n ? { ...item, [key]: value } : item))}/>)}<button type="button" onClick={() => update(i, 'sets', s.sets.filter((_, j) => n !== j))}>移除该组</button></div>)}<div className="actions"><button type="button" onClick={() => update(i, 'sets', [...s.sets, { task: '', repeats: '', distance: '', restSeconds: '' }])}>添加组</button><span>已填写总量：{s.sets.reduce((total, g) => total + Number(g.repeats || 0) * Number(g.distance || 0), 0)}m</span><button type="button" onClick={() => setSessions(current => current.filter((_, n) => n !== i))}>移除课次</button></div></fieldset>)}
      <div className="actions"><button type="button" onClick={() => setSessions(current => [...current, { id: `session-${Date.now()}-${current.length}`, date: '', type: '', title: '', durationMinutes: '', poolLength: '', startType: '', sets: [] }])}>添加课次 / 休息日</button><button disabled={busy} className="apple-btn apple-btn-primary">{busy ? '保存中…' : '保存计划版本'}</button><button type="button" onClick={() => downloadJSON('Nico-计划草稿.json', payload())}>导出草稿</button></div></form></details>}
    {data.planHistory?.length > 0 && <details className="glass-card"><summary>查看历史计划版本</summary>{data.planHistory.map((p, i) => <PlanCard key={`${p.id}-${p.version}-${i}`} plan={p}/>)}</details>}
  </div>;
}
export function PlanCard({ plan: p, onEdit, stale }) { return <article className="glass-card"><div className="flex-between"><h2>{p.title} · 版本{p.version}</h2>{onEdit && <button onClick={onEdit}>编辑新版本</button>}</div><p>{p.startDate}—{p.endDate} · {p.status} · 确认人：{p.reviewedBy || '未填写'}</p><h3>{p.focus}</h3>{stale && <Message>依据记录已更新，请教练复核本计划；旧版本仍保留。</Message>}{(p.sessions || []).map(s => <section className="session" key={s.id}><h3>{s.date} · {s.type} · {s.title}</h3><p>课次ID：{p.id}/{s.id} · 时长：{s.durationMinutes ?? '未填'}分钟 · {s.poolLength || '池长未填'} · {s.startType || '出发未填'}</p><ul>{s.sets.map((g, i) => <li key={i}>{g.task}：{g.repeats}×{g.distance}m，休息{g.restSeconds}s</li>)}</ul><strong>组表总量：{s.totalMeters ?? '未填写'}m</strong></section>)}<p className="muted">来源：{p.sourceVersion || '手动计划'} · {(p.sourceIds || []).join('、') || '尚未关联记录'} · 内容校验标识{fingerprint(p)}</p></article>; }
