import { downloadJSON } from '../services/files';
import { useState } from 'react';
import { WOMEN_50, STANDARD_SOURCE, STANDARD_VERSION, publicSnapshot } from '../../shared/domain.mjs';
import { Field, Message } from './ui';
import Records from './Records';
export default function Profile({ data, api, onSaved, reload, readOnly, role }) {
  const [profile, setProfile] = useState(data.profile), [publishing, setPublishing] = useState(data.publishing), [error, setError] = useState(''), [notice, setNotice] = useState(''), [busy, setBusy] = useState(false);
  const owner = role === 'owner';
  const [bases, setBases] = useState(() => ({ profile: api.getRevision(), publishing: api.getRevision() })), [conflict, setConflict] = useState('');
  const save = async (key, body) => { setBusy(true); setError(''); try { const saved = await api.request(`/api/${key}`, { method: 'PUT', body, expectedRevision: bases[key] }); onSaved(key, saved); setBases(current => ({ ...current, [key]: api.getRevision(), ...Object.fromEntries(Object.entries(current).filter(([, value]) => value === bases[key]).map(([name]) => [name, api.getRevision()])) })); setNotice('服务端保存成功'); } catch (problem) { setError(problem.message); if (problem.status === 409) setConflict(key); } finally { setBusy(false); } };
  const toggle = (key, id) => setPublishing(current => ({ ...current, [key]: current[key].includes(id) ? current[key].filter(x => x !== id) : [...current[key], id], confirmedBy: '', confirmedAt: '' }));
  const backup = async () => { try { downloadJSON('Nico-完整私有备份.json', await api.request('/api/backup')); } catch (problem) { setError(problem.message); } };
  const restore = async e => { const file = e.target.files[0]; if (!file) return; try { const body = JSON.parse(await file.text()); if (!window.confirm('用此备份恢复记录库？当前版本会自动备份，便于回退。')) return; await api.request('/api/restore', { method: 'POST', body }); await reload(); setNotice('已恢复；重新进入档案页查看最新字段'); } catch (problem) { setError(problem.message); } finally { e.target.value = ''; } };
  return <div className="stack"><header><h1>档案、目标与发布范围</h1><p className="muted">基础数据来自实际录入。性别与生日尚未确认时不自动匹配等级或计算年龄。</p></header><Message error>{error}</Message><Message>{notice}</Message>{conflict && <Message>请先刷新并核对最新档案 / 发布范围。<button onClick={() => { setBases(current => ({ ...current, [conflict]: api.getRevision() })); setConflict(''); }}>已核对当前版本，允许重试</button></Message>}
    <section className="glass-card"><h2>基础档案</h2>{owner ? <form onSubmit={e => { e.preventDefault(); save('profile', profile); }}><div className="form-grid">{[{ key: 'name', label: '姓名 / 昵称', type: 'text', required: true }, { key: 'sex', label: '已确认的性别', type: 'select', options: ['女', '男'] }, { key: 'birthDate', label: '生日（可留空）', type: 'date' }].map(f => <Field key={f.key} field={f} value={profile[f.key]} onChange={v => setProfile(current => ({ ...current, [f.key]: v }))}/>)}</div><button disabled={busy} className="apple-btn apple-btn-primary">保存已确认档案</button></form> : <p>{data.profile.name} · 性别{data.profile.sex || '未确认'} · 生日{data.profile.birthDate || '未填写'}</p>}</section>
    <section className="glass-card"><h2>女子50米项目官方参考表</h2><p>版本：{STANDARD_VERSION}。此表不自动推断档案性别，也不表示训练计时取得证书。其他项目请查官方完整表。</p><div className="history-table-container"><table className="history-table"><thead><tr><th>泳姿</th><th>池长</th><th>二级</th><th>三级</th></tr></thead><tbody>{Object.entries(WOMEN_50).flatMap(([stroke, pools]) => Object.entries(pools).map(([pool, lines]) => <tr key={`${stroke}-${pool}`}><td>{stroke}</td><td>{pool}</td><td>{lines.二级.toFixed(2)}秒</td><td>{lines.三级?.toFixed(2) || '查官方表'}</td></tr>))}</tbody></table></div><p><a href={STANDARD_SOURCE} target="_blank" rel="noreferrer">打开体育总局完整标准与赛事条件</a></p></section>
    <Records type="goals" data={data} api={api} onSaved={onSaved} readOnly={readOnly || !owner}/>
    {owner && <section className="glass-card"><h2>选择可公开内容</h2><p>公开端仅有成长故事、所选成绩与所选素材。原始身体、恢复、作息、目标备注和教练批注不会进入公开包。请确认素材涉及的其他儿童使用范围。</p><form onSubmit={e => { e.preventDefault(); save('publishing', publishing); }}><fieldset><legend>允许公开的成绩</legend>{data.swim.map(r => <label className="check-row" key={r.id}><input type="checkbox" checked={publishing.swimIds.includes(r.id)} onChange={() => toggle('swimIds', r.id)}/>{r.date} · {r.distance}{r.stroke} · {r.time} · {r.poolLength}池</label>)}</fieldset><fieldset><legend>允许公开的影像</legend>{data.media.map(m => <label className="check-row" key={m.id}><input type="checkbox" checked={publishing.mediaIds.includes(m.id)} onChange={() => toggle('mediaIds', m.id)}/>{m.date} · {m.title}</label>)}</fieldset><div className="form-grid">{[{ key: 'story', label: '公开成长故事（自行核对内容）', type: 'textarea' }, { key: 'confirmedBy', label: '发布范围确认人', type: 'text', required: true }, { key: 'confirmedAt', label: '范围确认日期', type: 'date', required: true }].map(f => <Field key={f.key} field={f} value={publishing[f.key]} onChange={v => setPublishing(current => ({ ...current, [f.key]: v, ...(f.key === 'story' ? { confirmedBy: '', confirmedAt: '' } : {}) }))}/>)}</div><div className="actions"><button disabled={busy} className="apple-btn apple-btn-primary">保存发布白名单</button><button type="button" onClick={() => downloadJSON('Nico-公开摘要预览.json', publicSnapshot(data, publishing))}>下载摘要预览</button></div><p className="muted">保存白名单不会自动发布网站。核对后生成本地发布包，构建与发布流程只读取这个包。</p><button type="button" onClick={async () => { try { const result = await api.request('/api/public-export', { method: 'POST' }); setNotice(result.message); } catch (problem) { setError(problem.message); } }}>用已保存白名单生成本地公开发布包</button></form></section>}
    {owner && <section className="glass-card"><h2>备份与恢复</h2><div className="actions"><button onClick={backup}>导出完整私有备份</button><label className="restore-label">从备份恢复<input type="file" accept="application/json" onChange={restore}/></label></div><p>每次修改前自动备份旧版本；原始录入文件保持原字节。备份包含私有资料，请自行妥善保存。</p><h3>回收站</h3>{(data.trash || []).length ? data.trash.map(item => <p key={item.id}>{item.collection} · {item.record.date || item.record.title} · {item.record.id} <button onClick={async () => { try { await api.request(`/api/trash/${item.id}/restore`, { method: 'POST' }); await reload(); } catch (problem) { setError(problem.message); } }}>恢复记录</button></p>) : <p className="muted">回收站为空。</p>}</section>}
  </div>;
}
