import { analysis, rangeSummary, fingerprint, STANDARD_SOURCE, STANDARD_VERSION, WOMEN_50 } from './domain.mjs';
const escape = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
export function reportHTML(state, start, end) {
  const result = analysis(state), summary = rangeSummary(state, start, end);
  const row = values => `<tr>${values.map(v => `<td>${escape(v)}</td>`).join('')}</tr>`;
  const table = (headers, rows) => `<table><thead>${row(headers)}</thead><tbody>${rows.length ? rows.map(row).join('') : row(['尚未录入'])}</tbody></table>`;
  return `<!doctype html><html lang="zh-CN"><meta charset="utf-8"><title>${escape(state.profile.name)}周期报告</title><style>body{font:16px/1.7 system-ui,sans-serif;max-width:960px;margin:30px auto;padding:20px;color:#18283b}h1,h2,h3{line-height:1.3}section{margin:28px 0}table{width:100%;border-collapse:collapse;font-size:14px}td{border:1px solid #ccd5df;padding:8px;overflow-wrap:anywhere}small{color:#536375}li{margin:10px 0}footer{border-top:1px solid #ccd5df;padding-top:20px}@media print{@page{size:A4;margin:16mm}body{margin:0;padding:0}h2,h3{break-after:avoid}tr{break-inside:avoid}thead{display:table-header-group}section{break-inside:auto}section.stage,li{break-inside:avoid}}</style><body>
  <h1>${escape(state.profile.name)} · 完整计划与周期报告</h1><p>记录范围：${escape(start)}—${escape(end)}；生成依据：${escape(result.version)}；报告标识：${fingerprint({ start, end, state })}</p><p>事实来自录入数据。建议草稿待教练确认；计划审核状态按原记录显示。</p>
  <section><h2>1. 本周期实际记录与覆盖</h2><p>水上训练${summary.trainings.length}条；泳程${summary.meters == null ? '未记录' : `${summary.meters}m（${summary.metersCount}条有泳程）`}；计划覆盖${summary.coverage == null ? '缺少已确认课次分母，无法计算' : `${summary.coverage}%`}；恢复${summary.nutrition.length}条；平均总睡眠${summary.sleep == null ? '未记录' : `${summary.sleep.toFixed(1)}小时（${summary.sleepCount}条）`}。</p>
  ${table(['日期', '距离/泳姿/池长', '成绩', '出发/计时', '原始备注'], summary.swim.map(r => [r.date, `${r.distance}/${r.stroke}/${r.poolLength}`, r.time, `${r.startType || '未知'}/${r.timingMethod || '未知'}`, r.notes || '']))}
  ${table(['日期', '课次', '实际时长', '实际泳程', '感受/不适', '教练原话', '来源ID'], summary.trainings.map(r => [r.date, r.session || '', r.durationMinutes ?? '未记录', r.totalMeters ?? '未记录', `${r.feeling || '未记录'}/${r.discomfort || '未记录'}`, r.coachNotes || '', r.id]))}${table(['日期', '总睡眠小时', '疲惫/不适/意愿', '原始备注', '来源ID'], summary.nutrition.map(r => [r.date, r.sleepHours ?? '未记录', `${r.fatigue || '未记录'}/${r.discomfort || '未记录'}/${r.willingness || '未记录'}`, r.notes || '', r.id]))}<h3>已录入测量（日期和方法不可省略）</h3>${table(['日期', '身高cm', '体重kg', '方法', '来源ID'], state.growth.map(r => [r.date, r.height ?? '未记录', r.weight ?? '未记录', r.measurementMethod || '未填写', r.id]))}${table(['日期', '跳远cm', '平板秒', '方法', '来源ID'], state.fitness.map(r => [r.date, r.standingJump ?? '未记录', r.plankSeconds ?? '未记录', r.measurementMethod || '未填写', r.id]))}</section>
  <section><h2>2. 当前数据分析与证据限制</h2><ul>${result.facts.map(f => `<li><strong>${escape(f.kind)}</strong>：${escape(f.text)}<br><small>依据：${escape(f.sourceIds.join('、') || '集合数量')}</small></li>`).join('')}</ul></section>
  <section><h2>3. 基于当前数据的4周提升建议</h2><p>主要重点：${escape(result.focus)}。具体训练量与动作由教练确认。</p>${result.stages.map(s => `<section class="stage"><h3>${escape(s.title)}</h3><p>${escape(s.action)}</p><p>交付：${escape(s.delivery)}；状态：建议草稿。</p></section>`).join('')}</section>
  <section><h2>4. 全部保存计划与完整课次</h2>${state.plans.length ? state.plans.map(p => `<section><h3>${escape(p.title)} · 版本${escape(p.version)}</h3><p>${escape(p.startDate)}—${escape(p.endDate)}；${escape(p.status)}；教练确认人：${escape(p.reviewedBy || '未填写')}</p><p>${escape(p.focus)}</p><p>计划备注：${escape(p.notes || '未填写')}</p>${(p.sessions || []).map(s => `<h4>${escape(s.date)} · ${escape(s.type)} · ${escape(s.title)}</h4><p>课次ID：${escape(p.id)}/${escape(s.id)}；${escape(s.poolLength || '池长未填')}；${escape(s.startType || '出发未填')}；${escape(s.durationMinutes ?? '未填')}分钟</p>${table(['任务', '次数', '每次距离m', '休息秒'], s.sets.map(g => [g.task, g.repeats, g.distance, g.restSeconds]))}<p>组表总量：${escape(s.totalMeters ?? '未填写')}m</p>`).join('')}<p>来源：${escape(p.sourceVersion || '手动计划')}；${escape((p.sourceIds || []).join('、'))}</p></section>`).join('') : '<p>尚无保存计划；建议草稿未被当作实际课表。</p>'}</section>
  <section><h2>5. 录像复盘与审核</h2>${state.annotations.length ? state.annotations.map(a => `<h3>${escape(state.media.find(m => m.id === a.mediaId)?.title || a.mediaId)} · ${escape(a.startSecond)}–${escape(a.endSecond)}秒</h3><p>运动员/泳道：${escape(a.athleteIdentity || '未确认')}；观察：${escape(a.observation)}</p><p>限制：${escape(a.limitation || '未填写')}；建议：${escape(a.suggestion || '未填写')}；状态：${escape(a.status)}；审核人：${escape(a.reviewedBy || '未填写')}</p>`).join('') : '<p>尚无时间点批注，不能声称已经完成个体技术分析。</p>'}</section>
  <section><h2>6. 等级标准与个人目标</h2><p>档案性别：${escape(state.profile.sex || '未确认')}；原始个人目标${state.goals.length}条保留在档案，不将未确认赛事/晋升规则当作训练指令。</p><p>以下为女子50米项目参考，未确认档案不自动匹配；达线、赛事资格与证书独立。版本${escape(STANDARD_VERSION)}。<a href="${STANDARD_SOURCE}">官方完整标准</a></p>${table(['50米泳姿', '池长', '二级秒', '三级秒'], Object.entries(WOMEN_50).flatMap(([stroke, pools]) => Object.entries(pools).map(([pool, lines]) => [stroke, pool, lines.二级, lines.三级 ?? '请查官方表'])) )}</section>
  <section><h2>7. 恢复与安全边界</h2><p>不布置家庭水下憋气任务、强制限气和统一补充剂处方；家庭额外运动计入总负荷。疼痛、不适或反复疲惫时先沟通现场教练和适当专业人员。体能无实测不评分。长池50米没有半程转身。</p></section>
  <footer>家庭报告包含私有记录，请按所需范围自行保存。公开展示使用独立字段白名单，与完整报告分开。</footer></body></html>`;
}
